
```
    1  apt-get update
    2  apt-get install sudo
    3  apt install -y --allow-unauthenticated openjdk-8-jre-headless && update-alternatives --config java && java -version
    4  export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/ && JRE_HOME=$JAVA_HOME/jre && export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar && export PATH="$PATH:$JAVA_HOME/bin"
    5  echo $JAVA_HOME
    6  /usr/lib/jvm/java-8-openjdk-amd64/bin/java -version
    7  ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && dpkg --configure -a
    8  apt -y install software-properties-common
    9  apt -y install maven
   10  apt -y install build-essential
   11  apt -y install cmake
   12  apt -y install libssl-dev
   13  apt -y install libre2-dev
   14  apt -y install libcurl4-openssl-dev
   15  apt -y install clang
   16  apt -y install lldb
   17  apt -y install lld
   18  apt -y install libz-dev
   19  apt -y install git
   20  apt -y install ninja-build
   21  apt -y install uuid-dev
   22  apt -y install autoconf-archive
   23  apt -y install curl zip unzip tar pkg-config bison libtool flex vim
   24  history | less
```
